try:
    # x=6
    print(x)

except:
    print("an errror occured")


finally:
    print("successful")